/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
  const val org_gradle_kotlin_kotlin_dsl_gradle_plugin: String =
    "org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:" +
      Versions.org_gradle_kotlin_kotlin_dsl_gradle_plugin

  const val de_fayard_buildsrcversions_gradle_plugin: String =
    "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
      Versions.de_fayard_buildsrcversions_gradle_plugin

  /**
   * https://kotlinlang.org/
   */
  const val org_jetbrains_kotlin_kotlin_stdlib_jdk8: String =
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" + Versions.org_jetbrains_kotlin_kotlin_stdlib_jdk8

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_scripting_compiler_embeddable: String =
    "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
      Versions.kotlin_scripting_compiler_embeddable

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_annotation_processing_gradle: String =
    "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" +
      Versions.kotlin_annotation_processing_gradle

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_android_extensions_runtime: String =
    "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" +
      Versions.kotlin_android_extensions_runtime

  /**
   * https://developer.android.com/studio
   */
  const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
    Versions.com_android_tools_build_gradle

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_android_extensions: String = "org.jetbrains.kotlin:kotlin-android-extensions:" +
    Versions.kotlin_android_extensions

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_sam_with_receiver: String = "org.jetbrains.kotlin:kotlin-sam-with-receiver:" +
    Versions.kotlin_sam_with_receiver

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val lifecycle_extensions: String = "androidx.lifecycle:lifecycle-extensions:" +
    Versions.lifecycle_extensions

  /**
   * https://junit.org/junit5/
   */
  const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api:" +
    Versions.org_junit_jupiter

  /**
   * https://junit.org/junit5/
   */
  const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine:" +
    Versions.org_junit_jupiter

  /**
   * http://tools.android.com
   */
  const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
    Versions.constraintlayout

  /**
   * https://github.com/mannodermaus/android-junit5
   */
  const val android_junit5: String = "de.mannodermaus.gradle.plugins:android-junit5:" +
    Versions.android_junit5

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:" +
    Versions.kotlin_reflect

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val room_compiler: String = "androidx.room:room-compiler:" + Versions.androidx_room

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val room_runtime: String = "androidx.room:room-runtime:" + Versions.androidx_room

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val room_testing: String = "androidx.room:room-testing:" + Versions.androidx_room

  /**
   * https://developer.android.com/testing
   */
  const val espresso_core: String = "androidx.test.espresso:espresso-core:" + Versions.espresso_core

  /**
   * http://developer.android.com/tools/extras/support-library.html
   */
  const val recyclerview: String = "androidx.recyclerview:recyclerview:" + Versions.recyclerview

  /**
   * https://developer.android.com/studio
   */
  const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

  /**
   * https://developer.android.com/jetpack/androidx
   */
  const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

  /**
   * http://developer.android.com/tools/extras/support-library.html
   */
  const val material: String = "com.google.android.material:material:" + Versions.material

  /**
   * https://github.com/google/dagger
   */
  const val dagger: String = "com.google.dagger:dagger:" + Versions.dagger

  /**
   * https://developer.android.com/studio
   */
  const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2
}
